import type { AppData } from "../types";
import { hashPassword, uid } from "./storage";

export async function seedInitialData(): Promise<AppData> {
  const adminHash = await hashPassword("Admin@123");
  const managerHash = await hashPassword("Manager@123");

  const now = new Date().toISOString();

  const adminId = uid("usr");
  const managerId = uid("usr");

  const users = [
    {
      id: adminId,
      username: "admin",
      fullName: "د سیستم مدیر / System Administrator",
      email: "admin@procurement.gov",
      role: "admin" as const,
      passwordHash: adminHash,
      createdAt: now,
      active: true,
    },
    {
      id: managerId,
      username: "manager",
      fullName: "د قراردادونو مدیر / Contracts Manager",
      email: "manager@procurement.gov",
      role: "manager" as const,
      passwordHash: managerHash,
      createdAt: now,
      active: true,
    },
  ];

  const c1 = uid("co");
  const c2 = uid("co");
  const c3 = uid("co");

  const companies = [
    {
      id: c1,
      name: "د کابل ساختماني شرکت",
      type: "construction" as const,
      registrationNo: "CON-2024-001",
      contactPerson: "احمد ولي",
      phone: "+93 700 123 456",
      email: "info@kabulcon.af",
      address: "کابل، شهر نو، سرک ۱۵",
      blacklisted: false,
      violations: [],
      experience: "۱۲ کاله د ساختماني پروژو تجربه",
      createdAt: now,
      createdBy: adminId,
    },
    {
      id: c2,
      name: "آریانا لوژستیک ګروپ",
      type: "logistics" as const,
      registrationNo: "LOG-2024-002",
      contactPerson: "محمد قاسم",
      phone: "+93 700 987 654",
      email: "contact@aryana-log.af",
      address: "کابل، تایمنی، سرک دریم",
      blacklisted: false,
      violations: [
        {
          id: uid("v"),
          date: now,
          description: "د قرارداد تخلف – ناوخت تسلیمي",
          severity: "medium" as const,
        },
      ],
      experience: "۸ کاله د لوژستیکي خدماتو تجربه",
      createdAt: now,
      createdBy: adminId,
    },
    {
      id: c3,
      name: "هرات ودانیز شرکت",
      type: "construction" as const,
      registrationNo: "CON-2024-003",
      contactPerson: "نقیب الله",
      phone: "+93 700 555 333",
      email: "herat@buildco.af",
      address: "هرات، ګذرگاه",
      blacklisted: true,
      blacklistReason: "د څو قراردادونو پرلپسې تخلف او د کیفیت ټیټوالی",
      violations: [],
      experience: "۵ کاله",
      createdAt: now,
      createdBy: adminId,
    },
  ];

  const contracts = [
    {
      id: uid("ct"),
      contractNo: "CT-2024-0001",
      companyId: c1,
      title: "د ښوونځي د ودانۍ جوړول – کابل",
      amount: 250000,
      currency: "USD" as const,
      tier: "tier3" as const,
      startDate: "2024-03-01",
      endDate: "2025-06-30",
      status: "active" as const,
      progressPercent: 45,
      description: "د ۱۲ ټولګیو ښوونځي جوړول",
      attachmentName: "contract-001.pdf",
      attachmentType: "pdf" as const,
      createdAt: now,
      createdBy: adminId,
    },
    {
      id: uid("ct"),
      contractNo: "CT-2024-0002",
      companyId: c2,
      title: "د کالیو د لیږد خدمتونه",
      amount: 35000,
      currency: "USD" as const,
      tier: "tier2" as const,
      startDate: "2024-05-15",
      endDate: "2024-12-31",
      status: "active" as const,
      progressPercent: 78,
      description: "د دفتري کالیو لیږد",
      attachmentName: "contract-002.xlsx",
      attachmentType: "excel" as const,
      createdAt: now,
      createdBy: managerId,
    },
    {
      id: uid("ct"),
      contractNo: "CT-2024-0003",
      companyId: c1,
      title: "د سرک ترمیم – ۲ کیلومتره",
      amount: 750000,
      currency: "USD" as const,
      tier: "tier4" as const,
      startDate: "2024-01-10",
      endDate: "2024-11-30",
      status: "completed" as const,
      progressPercent: 100,
      description: "د کابل – لوګر سرک ترمیم",
      attachmentName: "contract-003.pdf",
      attachmentType: "pdf" as const,
      createdAt: now,
      createdBy: adminId,
    },
  ];

  const orders = [
    {
      id: uid("or"),
      orderNo: "PO-2024-0001",
      title: "د دفتري سامان اخیستل",
      companyId: c2,
      category: "retail" as const,
      priority: "high" as const,
      status: "in_progress" as const,
      requestedDate: "2024-10-01",
      requiredDate: "2024-10-20",
      amount: 4500,
      description: "میز، چوکۍ، الماري",
      createdAt: now,
      createdBy: managerId,
    },
    {
      id: uid("or"),
      orderNo: "PO-2024-0002",
      title: "د کمپیوټرونو ترمیم",
      category: "retail" as const,
      priority: "urgent" as const,
      status: "pending" as const,
      requestedDate: "2024-10-15",
      requiredDate: "2024-10-25",
      amount: 2300,
      description: "۱۵ کمپیوټرونه",
      createdAt: now,
      createdBy: managerId,
    },
    {
      id: uid("or"),
      orderNo: "PO-2024-0003",
      title: "د جنراتور تیل تامینول",
      companyId: c2,
      category: "contract" as const,
      priority: "medium" as const,
      status: "incomplete" as const,
      requestedDate: "2024-09-10",
      requiredDate: "2024-09-30",
      amount: 12000,
      description: "د یوې میاشتې اړتیا",
      createdAt: now,
      createdBy: adminId,
    },
  ];

  const vendors = [
    {
      id: uid("vn"),
      accountNo: "ACC-N-1001",
      vendorName: "د کابل ساختماني شرکت",
      type: "construction" as const,
      taxId: "TIN-998877",
      bankAccount: "AZ-001-22-33-44",
      contactInfo: "+93 700 123 456 | info@kabulcon.af",
      createdAt: now,
    },
    {
      id: uid("vn"),
      accountNo: "ACC-N-1002",
      vendorName: "آریانا لوژستیک ګروپ",
      type: "logistics" as const,
      taxId: "TIN-554433",
      bankAccount: "AZ-002-55-66-77",
      contactInfo: "+93 700 987 654 | contact@aryana-log.af",
      createdAt: now,
    },
  ];

  // Seed Inventory Items
  const sampleItemId1 = uid("inv");
  const sampleItemId2 = uid("inv");
  const sampleItemId3 = uid("inv");
  const sampleItemId4 = uid("inv");

  const inventoryItems = [
    {
      id: sampleItemId1,
      code: "SMP-2024-001",
      name: "د سیمنټ نمونه / Cement Sample",
      type: "sample" as const,
      category: "ساختماني توکي",
      description: "د کیفیت ازموینې لپاره د سیمنټ نمونه",
      unit: "کڅوړه",
      quantity: 25,
      minStock: 10,
      maxStock: 100,
      reorderPoint: 15,
      location: "مخزن A - داخلې",
      batchNumber: "CM-2024-A45",
      receivedDate: now,
      condition: "new" as const,
      notes: "د تازه سیمنټ نمونه",
      createdAt: now,
      updatedAt: now,
      createdBy: adminId,
    },
    {
      id: sampleItemId2,
      code: "SMP-2024-002",
      name: "د اوسپنې نمونه / Steel Sample",
      type: "sample" as const,
      category: "ساختماني توکي",
      description: "د اوسپنې میلګردو ازموینې لپاره",
      unit: "عدد",
      quantity: 50,
      minStock: 20,
      maxStock: 200,
      reorderPoint: 30,
      location: "مخزن B - فلزات",
      batchNumber: "STL-2024-B12",
      receivedDate: now,
      condition: "new" as const,
      notes: "د ۱۲ میلی‌متري میلګردو نمونه",
      createdAt: now,
      updatedAt: now,
      createdBy: adminId,
    },
    {
      id: sampleItemId3,
      code: "EQP-2024-001",
      name: "لابراتوار تجهیزات / Lab Equipment",
      type: "equipment" as const,
      category: "تجهیزات",
      description: "د کیفیت کنټرول لابراتوار تجهیزات",
      unit: "ست",
      quantity: 3,
      minStock: 2,
      maxStock: 10,
      reorderPoint: 2,
      location: "لابراتوار",
      serialNumber: "LAB-EQP-2024-001",
      receivedDate: now,
      condition: "new" as const,
      notes: "د کمپریشن ټیسټ ماشین",
      createdAt: now,
      updatedAt: now,
      createdBy: adminId,
    },
    {
      id: sampleItemId4,
      code: "SUP-2024-001",
      name: "د دفتري سامان / Office Supplies",
      type: "supply" as const,
      category: "دفتري توکي",
      description: "د چاپیریال ساتنې لپاره دفتري سامان",
      unit: "بکس",
      quantity: 15,
      minStock: 5,
      maxStock: 50,
      reorderPoint: 10,
      location: "اداري مخزن",
      receivedDate: now,
      condition: "new" as const,
      notes: "د کاغذ، قلم، فولډر",
      createdAt: now,
      updatedAt: now,
      createdBy: adminId,
    },
  ];

  // Seed Inventory Movements
  const inventoryMovements = [
    {
      id: uid("mov"),
      itemId: sampleItemId1,
      type: "stock_in" as const,
      quantity: 25,
      previousQuantity: 0,
      newQuantity: 25,
      reference: "Initial stock",
      notes: "د سیستم پیل کې د نمونو ثبت",
      date: now,
      performedBy: adminId,
    },
    {
      id: uid("mov"),
      itemId: sampleItemId2,
      type: "stock_in" as const,
      quantity: 50,
      previousQuantity: 0,
      newQuantity: 50,
      reference: "Initial stock",
      notes: "د سیستم پیل کې د نمونو ثبت",
      date: now,
      performedBy: adminId,
    },
    {
      id: uid("mov"),
      itemId: sampleItemId3,
      type: "stock_in" as const,
      quantity: 3,
      previousQuantity: 0,
      newQuantity: 3,
      reference: "Initial stock",
      notes: "د سیستم پیل کې د تجهیزاتو ثبت",
      date: now,
      performedBy: adminId,
    },
  ];

  return {
    users,
    companies,
    contracts,
    orders,
    vendors,
    auditLogs: [],
    inventoryItems,
    inventoryMovements,
  };
}
